import type { Profile } from './gig-types';

const acceptedTermsAt = '2026-04-26T00:00:00.000Z';

const demoDefaults = {
  search_radius: 10,
  is_verified: true,
  is_onboarded: true,
  google_authenticated: true,
  phone_verified: true,
  accepted_terms_at: acceptedTermsAt,
  signup_bonus_awarded: true,
  bidder_access_unlocked_at: null,
  ai_match_profile: null,
  ai_match_profile_signature: null,
  ai_match_profile_location: null,
  ai_match_profile_updated_at: null,
} satisfies Partial<Profile>;

export const demoBypassProfiles: Profile[] = [
  {
    ...demoDefaults,
    id: 'profile-aria',
    username: 'Aria Stone',
    avatar_url: 'repo://demo/avatars/aria-stone.png',
    bio: 'Trusted Gigachad for event and home tasks around Rapid City.',
    skills: ['Events', 'Hospitality', 'Delivery'],
    interests: ['Events', 'Hospitality', 'Delivery', 'Cleaning', 'Errands'],
    credits: 550,
    location: { latitude: 44.0871, longitude: -103.2216 },
    phone_number: '+16055550184',
    birth_date: '1994-03-12',
    education_level: 'Bachelor degree',
    vouch_count: 17,
    posted_vouch_count: 29,
    rating: 4.84,
    rating_count: 46,
  },
  {
    ...demoDefaults,
    id: 'profile-milo',
    username: 'Milo Reyes',
    avatar_url: 'repo://demo/avatars/milo-reyes.png',
    bio: 'Handyman, installer, and weekend problem solver.',
    skills: ['Handywork', 'Tech Setup', 'Assembly'],
    interests: ['Handywork', 'Tech Setup', 'Assembly', 'Moving', 'Yard Work'],
    credits: 320,
    location: { latitude: 44.0696, longitude: -103.2458 },
    phone_number: '+16055550149',
    birth_date: '1991-11-08',
    education_level: 'Trade certification',
    vouch_count: 41,
    posted_vouch_count: 18,
    rating: 4.96,
    rating_count: 59,
  },
  {
    ...demoDefaults,
    id: 'profile-sage',
    username: 'Sage Kim',
    avatar_url: 'repo://demo/avatars/sage-kim.png',
    bio: 'Detail-focused cleaner and organizer.',
    skills: ['Cleaning', 'Organizing', 'Errands'],
    interests: ['Cleaning', 'Organizing', 'Errands', 'Pet Care', 'Admin'],
    credits: 260,
    location: { latitude: 44.1048, longitude: -103.2371 },
    phone_number: '+16055550190',
    birth_date: '1997-05-22',
    education_level: 'Some college',
    vouch_count: 36,
    posted_vouch_count: 14,
    rating: 4.88,
    rating_count: 50,
  },
  {
    ...demoDefaults,
    id: 'profile-juno',
    username: 'Juno Patel',
    avatar_url: 'repo://demo/avatars/juno-patel.png',
    bio: 'Reliable mover with a dolly and compact SUV.',
    skills: ['Moving', 'Delivery', 'Assembly'],
    interests: ['Moving', 'Delivery', 'Assembly', 'Events', 'Auto Help'],
    credits: 420,
    location: { latitude: 44.052, longitude: -103.1937 },
    phone_number: '+16055550132',
    birth_date: '1996-09-01',
    education_level: 'Associate degree',
    vouch_count: 53,
    posted_vouch_count: 9,
    rating: 4.98,
    rating_count: 62,
  },
];
