import type { GigMatch, Message, Profile, Task } from './gig-types';

export const currentUser: Profile = {
  id: 'profile-me',
  username: 'Nova Carter',
  avatar_url: null,
  bio: 'Fast local helper for moving, errands, setup, and event ops.',
  skills: ['Moving', 'Cleaning', 'Events', 'Tech Setup'],
  credits: 18,
  location: { latitude: 39.7392, longitude: -104.9903 },
  search_radius: 8,
  is_verified: false,
  vouch_count: 24,
  rating: 4.92,
};

export const profiles: Profile[] = [
  currentUser,
  {
    id: 'profile-aria',
    username: 'Aria Stone',
    avatar_url: null,
    bio: 'Verified poster with same-day event and home tasks.',
    skills: ['Events', 'Hospitality'],
    credits: 32,
    location: { latitude: 39.751, longitude: -104.999 },
    search_radius: 10,
    is_verified: true,
    vouch_count: 17,
    rating: 4.84,
  },
  {
    id: 'profile-milo',
    username: 'Milo Reyes',
    avatar_url: null,
    bio: 'Handyman, installer, and weekend problem solver.',
    skills: ['Handywork', 'Tech Setup', 'Assembly'],
    credits: 9,
    location: { latitude: 39.727, longitude: -104.982 },
    search_radius: 12,
    is_verified: true,
    vouch_count: 41,
    rating: 4.96,
  },
  {
    id: 'profile-sage',
    username: 'Sage Kim',
    avatar_url: null,
    bio: 'Detail-focused cleaner and organizer.',
    skills: ['Cleaning', 'Organizing', 'Errands'],
    credits: 14,
    location: { latitude: 39.746, longitude: -105.006 },
    search_radius: 6,
    is_verified: true,
    vouch_count: 36,
    rating: 4.88,
  },
  {
    id: 'profile-juno',
    username: 'Juno Patel',
    avatar_url: null,
    bio: 'Reliable mover with a dolly and compact SUV.',
    skills: ['Moving', 'Delivery', 'Assembly'],
    credits: 11,
    location: { latitude: 39.733, longitude: -104.973 },
    search_radius: 8,
    is_verified: true,
    vouch_count: 53,
    rating: 4.98,
  },
];

export const tasks: Task[] = [
  {
    id: 'task-setup-booth',
    poster_id: 'profile-aria',
    title: 'Set up a pop-up booth downtown',
    description:
      'Need help unloading two folding tables, staging product trays, and running a compact checkout stand before doors open.',
    budget: 92,
    category: 'Events',
    location: { latitude: 39.7487, longitude: -104.9954 },
    required_skills: ['Events', 'Moving', 'Tech Setup', 'Hospitality'],
    is_boosted: true,
    created_at: '2026-04-24T17:00:00.000Z',
  },
  {
    id: 'task-router',
    poster_id: 'profile-milo',
    title: 'Install mesh Wi-Fi and tidy cables',
    description:
      'Three-node mesh kit is already purchased. Need setup, speed test, and cable routing behind the media console.',
    budget: 75,
    category: 'Tech',
    location: { latitude: 39.7321, longitude: -104.9878 },
    required_skills: ['Tech Setup', 'Handywork'],
    is_boosted: true,
    created_at: '2026-04-24T18:10:00.000Z',
  },
  {
    id: 'task-studio-reset',
    poster_id: 'profile-sage',
    title: 'Reset photo studio after shoot',
    description:
      'Sweep, pack two softboxes, wipe counters, and move a backdrop stand into storage. Building has freight elevator.',
    budget: 64,
    category: 'Cleaning',
    location: { latitude: 39.7562, longitude: -104.9864 },
    required_skills: ['Cleaning', 'Moving', 'Organizing'],
    is_boosted: false,
    created_at: '2026-04-24T15:25:00.000Z',
  },
  {
    id: 'task-market-run',
    poster_id: 'profile-aria',
    title: 'Pick up catering boxes',
    description:
      'Grab prepaid catering boxes from LoDo and deliver to a venue lobby. Must arrive between 4:00 and 4:30.',
    budget: 48,
    category: 'Errands',
    location: { latitude: 39.754, longitude: -104.997 },
    required_skills: ['Delivery', 'Errands', 'Events'],
    is_boosted: false,
    created_at: '2026-04-24T14:00:00.000Z',
  },
  {
    id: 'task-patio',
    poster_id: 'profile-milo',
    title: 'Assemble patio chairs',
    description:
      'Four boxed chairs, tools provided. Prefer someone who can finish today and take packaging to the trash room.',
    budget: 58,
    category: 'Assembly',
    location: { latitude: 39.7218, longitude: -104.9725 },
    required_skills: ['Assembly', 'Handywork', 'Moving'],
    is_boosted: false,
    created_at: '2026-04-24T13:15:00.000Z',
  },
  {
    id: 'task-my-garage',
    poster_id: 'profile-me',
    title: 'Help sort a garage shelf',
    description:
      'One-hour organization sprint. Move bins, label holiday boxes, and bring light donation bags to the curb.',
    budget: 42,
    category: 'Home',
    location: { latitude: 39.7392, longitude: -104.9903 },
    required_skills: ['Organizing', 'Moving'],
    is_boosted: false,
    created_at: '2026-04-24T12:15:00.000Z',
  },
];

export const matches: GigMatch[] = [
  {
    id: 'match-locked-chat',
    task_id: 'task-router',
    doer_id: 'profile-me',
    bid_note: 'I can knock this out after lunch and verify speeds on each floor.',
    is_unlocked: false,
    status: 'matched',
    created_at: '2026-04-24T19:00:00.000Z',
  },
  {
    id: 'match-poster-review',
    task_id: 'task-my-garage',
    doer_id: 'profile-juno',
    bid_note: 'I have a dolly and can be there in 25 minutes.',
    is_unlocked: false,
    status: 'pending',
    created_at: '2026-04-24T18:45:00.000Z',
  },
  {
    id: 'match-completed',
    task_id: 'task-studio-reset',
    doer_id: 'profile-me',
    bid_note: 'I have event reset experience and can bring microfiber cloths.',
    is_unlocked: true,
    status: 'completed',
    created_at: '2026-04-23T21:30:00.000Z',
  },
];

export const messages: Message[] = [
  {
    id: 'message-router-1',
    match_id: 'match-locked-chat',
    sender_id: 'profile-milo',
    content: 'Great profile. I liked you back for the Wi-Fi install.',
    created_at: '2026-04-24T19:02:00.000Z',
  },
  {
    id: 'message-router-2',
    match_id: 'match-locked-chat',
    sender_id: 'profile-me',
    content: 'Perfect. I can bring a cable tester too.',
    created_at: '2026-04-24T19:03:00.000Z',
  },
  {
    id: 'message-studio-1',
    match_id: 'match-completed',
    sender_id: 'profile-sage',
    content: 'Thanks again. Studio was spotless.',
    created_at: '2026-04-23T23:20:00.000Z',
  },
];
