import type { GigMatch, Message, Profile, Task } from './gig-types';
import { DEFAULT_TASK_RADIUS_MILES, RAPID_CITY_CENTER } from './geo';

export const currentUser: Profile = {
  id: 'profile-me',
  username: '',
  avatar_url: null,
  bio: '',
  skills: [],
  interests: [],
  credits: 0,
  location: RAPID_CITY_CENTER,
  search_radius: DEFAULT_TASK_RADIUS_MILES,
  is_verified: false,
  is_onboarded: false,
  google_authenticated: false,
  phone_number: '',
  phone_verified: false,
  birth_date: '',
  education_level: null,
  accepted_terms_at: null,
  signup_bonus_awarded: false,
  daily_streak: 6,
  weekly_streak: 0,
  monthly_streak: 0,
  last_reward_claimed_at: null,
  vouch_count: 24,
  posted_vouch_count: 8,
  rating: 4.92,
};

export const profiles: Profile[] = [
  currentUser,
  {
    id: 'profile-aria',
    username: 'Aria Stone',
    avatar_url: null,
    bio: 'Verified gig starter with same-day event and home tasks.',
    skills: ['Events', 'Hospitality', 'Delivery'],
    interests: ['Events', 'Hospitality', 'Delivery', 'Cleaning', 'Errands'],
    credits: 32,
    location: { latitude: 44.0871, longitude: -103.2216 },
    search_radius: 10,
    is_verified: true,
    is_onboarded: true,
    google_authenticated: true,
    phone_number: '+1 605 555 0184',
    phone_verified: true,
    birth_date: '1994-03-12',
    education_level: 'Bachelor degree',
    accepted_terms_at: '2026-04-01T16:00:00.000Z',
    signup_bonus_awarded: true,
    daily_streak: 13,
    weekly_streak: 1,
    monthly_streak: 0,
    last_reward_claimed_at: '2026-04-24T13:00:00.000Z',
    vouch_count: 17,
    posted_vouch_count: 29,
    rating: 4.84,
  },
  {
    id: 'profile-milo',
    username: 'Milo Reyes',
    avatar_url: null,
    bio: 'Handyman, installer, and weekend problem solver.',
    skills: ['Handywork', 'Tech Setup', 'Assembly'],
    interests: ['Handywork', 'Tech Setup', 'Assembly', 'Moving', 'Yard Work'],
    credits: 9,
    location: { latitude: 44.0696, longitude: -103.2458 },
    search_radius: 12,
    is_verified: true,
    is_onboarded: true,
    google_authenticated: true,
    phone_number: '+1 605 555 0149',
    phone_verified: true,
    birth_date: '1991-11-08',
    education_level: 'Trade certification',
    accepted_terms_at: '2026-04-02T18:00:00.000Z',
    signup_bonus_awarded: true,
    daily_streak: 21,
    weekly_streak: 3,
    monthly_streak: 0,
    last_reward_claimed_at: '2026-04-24T12:30:00.000Z',
    vouch_count: 41,
    posted_vouch_count: 18,
    rating: 4.96,
  },
  {
    id: 'profile-sage',
    username: 'Sage Kim',
    avatar_url: null,
    bio: 'Detail-focused cleaner and organizer.',
    skills: ['Cleaning', 'Organizing', 'Errands'],
    interests: ['Cleaning', 'Organizing', 'Errands', 'Pet Care', 'Admin'],
    credits: 14,
    location: { latitude: 44.1048, longitude: -103.2371 },
    search_radius: 6,
    is_verified: true,
    is_onboarded: true,
    google_authenticated: true,
    phone_number: '+1 605 555 0190',
    phone_verified: true,
    birth_date: '1997-05-22',
    education_level: 'Some college',
    accepted_terms_at: '2026-04-03T15:45:00.000Z',
    signup_bonus_awarded: true,
    daily_streak: 8,
    weekly_streak: 1,
    monthly_streak: 0,
    last_reward_claimed_at: '2026-04-24T09:00:00.000Z',
    vouch_count: 36,
    posted_vouch_count: 14,
    rating: 4.88,
  },
  {
    id: 'profile-juno',
    username: 'Juno Patel',
    avatar_url: null,
    bio: 'Reliable mover with a dolly and compact SUV.',
    skills: ['Moving', 'Delivery', 'Assembly'],
    interests: ['Moving', 'Delivery', 'Assembly', 'Events', 'Auto Help'],
    credits: 11,
    location: { latitude: 44.052, longitude: -103.1937 },
    search_radius: 8,
    is_verified: true,
    is_onboarded: true,
    google_authenticated: true,
    phone_number: '+1 605 555 0132',
    phone_verified: true,
    birth_date: '1996-09-01',
    education_level: 'Associate degree',
    accepted_terms_at: '2026-04-05T11:20:00.000Z',
    signup_bonus_awarded: true,
    daily_streak: 30,
    weekly_streak: 4,
    monthly_streak: 1,
    last_reward_claimed_at: '2026-04-24T08:30:00.000Z',
    vouch_count: 53,
    posted_vouch_count: 9,
    rating: 4.98,
  },
];

export const tasks: Task[] = [
  {
    id: 'task-setup-booth',
    poster_id: 'profile-aria',
    title: 'Set up a pop-up booth downtown',
    description:
      'Need help unloading two folding tables, staging product trays, and running a compact checkout stand before doors open.',
    budget: 92,
    category: 'Events',
    location_label: 'Downtown Rapid City',
    location: { latitude: 44.0814, longitude: -103.2295 },
    required_skills: ['Events', 'Moving', 'Tech Setup', 'Hospitality'],
    image_urls: ['https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80'],
    is_boosted: true,
    boost_days: 3,
    boost_cost_bsts: 9,
    date_window: 'Apr 27, 8:00 AM - 10:00 AM',
    status: 'open',
    created_at: '2026-04-24T17:00:00.000Z',
  },
  {
    id: 'task-router',
    poster_id: 'profile-milo',
    title: 'Install mesh Wi-Fi and tidy cables',
    description:
      'Three-node mesh kit is already purchased. Need setup, speed test, and cable routing behind the media console.',
    budget: 75,
    category: 'Tech Setup',
    location_label: 'West Boulevard area',
    location: { latitude: 44.0687, longitude: -103.2479 },
    required_skills: ['Tech Setup', 'Handywork'],
    image_urls: ['https://images.unsplash.com/photo-1606904825846-647eb07f5be2?auto=format&fit=crop&w=900&q=80'],
    is_boosted: true,
    boost_days: 2,
    boost_cost_bsts: 6,
    date_window: 'Apr 26 - Apr 28',
    status: 'open',
    created_at: '2026-04-24T18:10:00.000Z',
  },
  {
    id: 'task-studio-reset',
    poster_id: 'profile-sage',
    title: 'Reset photo studio after shoot',
    description:
      'Sweep, pack two softboxes, wipe counters, and move a backdrop stand into storage. Building has freight elevator.',
    budget: 64,
    category: 'Cleaning',
    location_label: 'North Rapid studio row',
    location: { latitude: 44.1032, longitude: -103.2386 },
    required_skills: ['Cleaning', 'Moving', 'Organizing'],
    image_urls: ['https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80'],
    is_boosted: false,
    boost_days: 0,
    boost_cost_bsts: 0,
    date_window: 'Finished Apr 23',
    status: 'archived',
    created_at: '2026-04-24T15:25:00.000Z',
  },
  {
    id: 'task-market-run',
    poster_id: 'profile-aria',
    title: 'Pick up catering boxes',
    description:
      'Grab prepaid catering boxes and deliver to a venue lobby. Must arrive between 4:00 and 4:30.',
    budget: 48,
    category: 'Errands',
    location_label: 'East North Street',
    location: { latitude: 44.0848, longitude: -103.1984 },
    required_skills: ['Delivery', 'Errands', 'Events'],
    image_urls: ['https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80'],
    is_boosted: false,
    boost_days: 0,
    boost_cost_bsts: 0,
    date_window: 'Apr 27, 4:00 PM - 4:30 PM',
    status: 'open',
    created_at: '2026-04-24T14:00:00.000Z',
  },
  {
    id: 'task-patio',
    poster_id: 'profile-milo',
    title: 'Assemble patio chairs',
    description:
      'Four boxed chairs, tools provided. Prefer someone who can finish today and take packaging to the trash room.',
    budget: 58,
    category: 'Assembly',
    location_label: 'Robbinsdale',
    location: { latitude: 44.0482, longitude: -103.2564 },
    required_skills: ['Assembly', 'Handywork', 'Moving'],
    image_urls: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80'],
    is_boosted: false,
    boost_days: 0,
    boost_cost_bsts: 0,
    date_window: 'Apr 25 - Apr 26',
    status: 'open',
    created_at: '2026-04-24T13:15:00.000Z',
  },
  {
    id: 'task-my-garage',
    poster_id: 'profile-me',
    title: 'Help sort a garage shelf',
    description:
      'One-hour organization sprint. Move bins, label holiday boxes, and bring light donation bags to the curb.',
    budget: 42,
    category: 'Organizing',
    location_label: 'Founders Park',
    location: RAPID_CITY_CENTER,
    required_skills: ['Organizing', 'Moving'],
    image_urls: ['https://images.unsplash.com/photo-1592503254549-d83d24a4dfab?auto=format&fit=crop&w=900&q=80'],
    is_boosted: false,
    boost_days: 0,
    boost_cost_bsts: 0,
    date_window: 'Apr 26, flexible',
    status: 'open',
    created_at: '2026-04-24T12:15:00.000Z',
  },
];

export const matches: GigMatch[] = [
  {
    id: 'match-locked-chat',
    task_id: 'task-router',
    doer_id: 'profile-me',
    bid_note: 'I can knock this out after lunch and verify speeds on each floor.',
    counter_bid: 80,
    availability_window: 'Apr 26, 1:00 PM - 4:00 PM',
    is_unlocked: false,
    status: 'matched',
    created_at: '2026-04-24T19:00:00.000Z',
  },
  {
    id: 'match-poster-review',
    task_id: 'task-my-garage',
    doer_id: 'profile-juno',
    bid_note: 'I have a dolly and can be there in 25 minutes.',
    counter_bid: 46,
    availability_window: 'Apr 26, 11:00 AM - 1:00 PM',
    is_unlocked: false,
    status: 'pending',
    created_at: '2026-04-24T18:45:00.000Z',
  },
  {
    id: 'match-completed',
    task_id: 'task-studio-reset',
    doer_id: 'profile-me',
    bid_note: 'I have event reset experience and can bring microfiber cloths.',
    counter_bid: 64,
    availability_window: 'Apr 23, 6:00 PM - 8:00 PM',
    is_unlocked: true,
    status: 'completed',
    created_at: '2026-04-23T21:30:00.000Z',
  },
];

export const messages: Message[] = [
  {
    id: 'message-router-1',
    match_id: 'match-locked-chat',
    sender_id: 'profile-milo',
    content: 'Great profile. I liked you back for the Wi-Fi install.',
    created_at: '2026-04-24T19:02:00.000Z',
  },
  {
    id: 'message-router-2',
    match_id: 'match-locked-chat',
    sender_id: 'profile-me',
    content: 'Perfect. I can bring a cable tester too.',
    created_at: '2026-04-24T19:03:00.000Z',
  },
  {
    id: 'message-studio-1',
    match_id: 'match-completed',
    sender_id: 'profile-sage',
    content: 'Thanks again. Studio was spotless.',
    created_at: '2026-04-23T23:20:00.000Z',
  },
];
